version: '3'
services:
  wtm_api:
    image: wtmapi:v1
    networks:
      - wtmnet
    environment:
      - DATABASE_URL=mongodb://ecalhoun2024wtm:Calhoun2024%21%24%5E%2A@35.169.199.129:27017/Events?authSource=admin
    ports:
      - "3000:3000"

networks:
  wtmnet:
    external: true
